services:
  premadepc-website:
    container_name: premadepc-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:443"
    environment:
      NODE_ENV: production
      HOST: '0.0.0.0'
      PORT: '443'
    restart: always
